### ISSUE TITLE
Change down to play status automatically

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#116]
It could be helpful to change the down to play status after some time on non-use to not down to play.
Somebody is down to play, forgot to undo it when he leaves and after some hours or when he sign out, tolaria changes it to not down to play.

**Comment by merhans123** [comment]
Maybe do the same for "is online" / "away"

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/26625f5f3adc0c9cd4de87f66ee4996d3fd36d55

Will be deployed with **sprint 5**
