### ISSUE TITLE
Players shown in the Players List

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#117]
I was searching for a player and it took really long until i noticed, you cant see online/away + offline player at the same time.
Maybe you can make this the default listing (show online/away + offline) with the option to filter for one or add an option to filter for both?

**Comment by Slanfan** [comment]
Yes, I know this is somewhat awkward and should really be fixed. I was just deploying a none final version. But having this issue to follow up is great 👍🏽

**Comment by Slanfan** [comment]
Should have been fixed with the deployment of release 0.9.6b
