### ISSUE TITLE
Font Color, in Tournament Organizing

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#118]
Using the funktion "Add tolaria Player", Dark layout, the Player names aren't shown, so maybe change the font color will fix it?

![add tolaria player](https://user-images.githubusercontent.com/77571615/104902889-962a3800-597f-11eb-84cc-9ef9b6095d9c.jpg)

**Comment by Slanfan** [comment]
I have already fixed this. just waiting to be released with a bunch of other improvements and bug-fixes.
