### ISSUE TITLE
Invited player cant join a non public Event

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#133]
I did two non public events and invited the tolaria player correctly and i saw them as attending players, but they cant click on the event. See pic below
![WhatsApp Image 2021-01-28 at 11 20 09](https://user-images.githubusercontent.com/77571615/106124311-3c81f480-615b-11eb-8387-4754f27a662f.jpeg)

**Comment by Slanfan** [comment]
This is now fixed. Any INVITED player or ATTENDING player can now enter the event.
