### ISSUE TITLE
webcam format

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#134]
Different visible areas from whereby and tolaria
![Bildschirmfoto 2021-01-28 um 20 50 27](https://user-images.githubusercontent.com/77571615/106197178-a974a900-61b2-11eb-948b-1877fd1d8305.png)
![Bildschirmfoto 2021-01-28 um 21 49 02](https://user-images.githubusercontent.com/77571615/106197185-ad083000-61b2-11eb-946d-31d9cf0f53a5.png)

**Comment by Slanfan** [comment]
What do you think about this @JonnieHedkvist?

I was also thinking the local video and remote video maybe should live in separate components if that is possible.

**Comment by Slanfan** [comment]
@merhans123 This is as intended. We have a 16:8 ratio on the video @ tolaria and Whereby I believe has the standard 16:9 ratio on their video. Usually, this is no biggie as players adjust their play area to what is visible on their screen.
