### ISSUE TITLE
Can’t toggle my video off

### ISSUE THREAD

**Issue by Slanfan** [Slanfan/MTG-Tolaria#141]
During yesterday's testing I found out that it's impossible to toggle the video off. 
I press the video button or the off switch in the video popover but nothing happens other than a log to the console.

**Comment by merhans123** [comment]
The same was today with microphone off or microphone on, when i was spectating as an TO.
Also i cant click on the Pop up button, when you @ a name in messages.
Sounds similar or?

**Comment by Slanfan** [comment]
Should have been fixed in the major overhaul
