### ISSUE TITLE
Card Search in Match Chat doesnt reset

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#143]
When somebody uses the card search in his table chat, all other tables see it too and it wont reset after the match.
You see the whole event all card searchs.

**Comment by Slanfan** [comment]
@merhans123 do you have an example event that I can check?
Maybe a screenshot?

**Comment by merhans123** [comment]
As you see, the player searching for the cards wasnt my opponen. 

<img width="1261" alt="Bildschirmfoto 2021-02-05 um 19 50 36" src="https://user-images.githubusercontent.com/77571615/107076335-96358f00-67eb-11eb-8358-14bec77bace1.png">

**Comment by merhans123** [comment]
You can check out this event, i left it open.
EVENT: FNM 05.02. Philly

**Comment by Slanfan** [comment]
@merhans123  thanks.
Found out I have missed filtering on the match document number. It should now only show messages connected to the same match document.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/f68900cadee7595738c769cd481348e72dc818d4
Fix will be deployed at a later stage.
