### ISSUE TITLE
Deckpic Upload custom ratio

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#144]
I wanted to upload my Deckpic, sadly it wasnt fitting the standard ratio and it was cut. Isnt there the possible to add a custom ratio or more standard ratios to choose?
![Bildschirmfoto 2021-01-31 um 11 51 32](https://user-images.githubusercontent.com/77571615/106387966-a1984d00-63dc-11eb-89e6-300134bf3a1e.png)

**Comment by Slanfan** [comment]
This should be fixed since some time back. The pics are automatically padded to be 16:9 format before being able to crop.
