### ISSUE TITLE
Leave Event Messages after the Event is closed or hide it.

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#145]
I am not sure, i mentioned this already, but you cant leave / delete closed event group messages.
At least a hide option would be great.

**Comment by Slanfan** [comment]
Fixed. Fetched the event information and added two properties to the event information data.
isEventChat + eventEnded.
If both flags are true then players may leave the event message group.

https://github.com/Slanfan/Tolaria/commit/bd9f50c844e29f249da15715b693dc6f4e36a669

**Comment by Slanfan** [comment]
Will be deployed at a later stage.
