### ISSUE TITLE
"Cropped" Dashboard on low Resolution Screens

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#150]
Cropped dashboard on a screen with a low resolution (1280x1024).
No horizontal Scroll bar

for me, the other parts are fine (Play, events, Players, messages arent cropped)

Pic 1, 80% Zoom
Pic 2, 100% Zoom 

Same Issue for discord user Kalabalik
![Screenshot 80% zoom](https://user-images.githubusercontent.com/77571615/106915368-36b18380-6706-11eb-9183-e314677b291e.jpg)
![Screenshot 100% zoom](https://user-images.githubusercontent.com/77571615/106915373-37e2b080-6706-11eb-8e0c-89149c4d7b89.jpg)

**Comment by Slanfan** [comment]
Solved and deployed. No version update just deployed as this was only one line of styling needed to show the horizontal scrollbar.
