### ISSUE TITLE
Stacking of text / Players

### ISSUE THREAD

**Issue by caboking** [Slanfan/MTG-Tolaria#151]
There is a small bug of stacking, when hovering a players "message" icon in the left column. Same  issue appears to be when you click on a player in "down to play" area and hover the "message", "collection" icons.

**Comment by Slanfan** [comment]
Thanks for reporting. Can you elaborate some more?
What are we expecting and what is happening?

**Comment by caboking** [comment]
Maybe this can explain it better.


Med venlig hilsen / Kind Regards

David Hugo Cabo
Architect / Photographer
+45 52 82 93 55
+47 93 64 57 80

www.davidhugocabo.com <http://www.davidhugocabo.com/>

**Comment by caboking** [comment]
<img width="537" alt="Skjermbilde 2021-02-05 kl  22 04 09" src="https://user-images.githubusercontent.com/78591697/107089671-4e206780-67ff-11eb-945a-06b83bdae6ab.png">
![Uploading Skjermbilde 2021-02-04 kl. 21.58.36.png…]()

**Comment by caboking** [comment]
<img width="703" alt="Skjermbilde 2021-02-04 kl  21 58 30" src="https://user-images.githubusercontent.com/78591697/107089709-61333780-67ff-11eb-94b8-45d31f8d2fc0.png">

**Comment by Slanfan** [comment]
Corrected the alignments of the tooltips.

![image](https://user-images.githubusercontent.com/9950323/107097299-f2f57180-680c-11eb-8706-d4da09f0437d.png)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/096193ef6e533a273783c2f947a897a26009efb8

It Will be deployed soon, fix is pushed to the master branch.
