### ISSUE TITLE
Limited Event should not require a ruleset

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#152]
![limited no ruleset](https://user-images.githubusercontent.com/77571615/107029557-7da78380-67af-11eb-8a9b-ceb49e419480.jpg)

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/107097955-60ee6880-680e-11eb-8161-f4bfec162789.png)

Solved and will be released at a later stage.
https://github.com/Slanfan/Tolaria/commit/54314d1181bc75d7babffd4c254b75e062e7cc1d
