### ISSUE TITLE
Can't see other peoples video

### ISSUE THREAD

**Issue by Turtlehatten** [Slanfan/MTG-Tolaria#155]
Dear Slanfan
First and foremost. What an awesome job on Tolaria, nice work! However, I'm experiencing some issues playing with other people. Yesterday, I was testing out the site with Jesper Therkildsen (I think he called you about it), and I couldn't see him in the room. We had tried a week prior, and I had the same issue there. I've tried 2 different computers, with both Chrome and Firefox, and I have also tried with mobile 4G hotspot, since we are having some provider issues in the city I live in. Both computers are Lenovo, one is setup by the school I work at. The other is totally incognito.

Kind regards
Esben

**Comment by Slanfan** [comment]
Hi.

Did you have the same issue with both 4G and standard ISP (internet service provider)?

If possible, could you state both providers?
In addition, do you have any issues with whereby or similar services?

**Comment by Turtlehatten** [comment]
Hi

Yes, same issue with both 4g and WiFi. My 4g provider is telmore og
fiberconnection is Stofa.
I've never had issues with Whereby.

søn. 14. feb. 2021 20.28 skrev Slanfan <notifications@github.com>:

**Comment by Turtlehatten** [comment]
Hi again
Its working for me now
