### ISSUE TITLE
Manual Pairings

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#158]
I paired Round 1 manually, because two people werent able to play round 1 and in Round 2 i used autopairings and i got one pairing from round 1 again, so i had to change pairings manually again.

Should tolaria remember the manual pairings and avoid them in the next rounds?

**Comment by Slanfan** [comment]
So you basically paired everyone manually and paired the "NON-playing" players against each other?

**Comment by merhans123** [comment]
I did normal pairing, changed the non playing player to play against each other and paired the other two guys who are playing against each other.

round 2, the other two guys just got paired against each other again.

**Comment by Slanfan** [comment]
Do you have the event Id?

You can copy it from the bottom of the organizer panel inside the event.

**Comment by Slanfan** [comment]
Can't seem to replicate this. Need more investigation. Will close and we can re-open if we encounter this again.
