### ISSUE TITLE
Filter settings should be stored

### ISSUE THREAD

**Issue by Slanfan** [Slanfan/MTG-Tolaria#167]
In a single session, the event filter settings should be stored. If I enter an event and then navigate back to the event list, the filter options are restored to default. These should remain as before.

**Comment by merhans123** [comment]
And i think the default status of the event filter need some tweaking. When you choose status ended, you have to choose date all past (or something similar) too, so see ended old events. I understand to not show all events by the default, but maybe you can add an if clause for the filter (if status ended, than set Date to all or so)
The same is for show todays events in progress per default.

**Comment by Slanfan** [comment]
Note to self: The filter options should be stored within the EventService so that they are "global" and accessible from other places as well. In addition, they would be the same throughout the whole session.

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/107946121-ddacdf80-6f90-11eb-8efb-77767b3179c7.png)

**Comment by Slanfan** [comment]
Changed where the filter settings are stored and added a date selection instead for time selection instead of the drop-down with fixed intervals.

https://github.com/Slanfan/Tolaria/commit/824bc301f50c3fe318af08ea5c51f46407ddd6c2
