### ISSUE TITLE
Allow auto-complete usernames to be clicked

### ISSUE THREAD

**Issue by michael-vandyke** [Slanfan/MTG-Tolaria#178]
When typing a username using the "@" tagging symbol, you have to press enter to complete the tag. I assumed I could also click on them, but they seem to unclickable.

**Comment by Slanfan** [comment]
![MTG-Tolaria-issues-178](https://user-images.githubusercontent.com/9950323/108644121-f72cba80-74ad-11eb-9e00-d17164952b5d.gif)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/87/commits/0433ed91e1a00fb0d2af856c3ab4a0f992230c3c
