### ISSUE TITLE
Messaging interface quirks

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#181]
The UX for messaging could use a couple of improvements:

- It's not easy to close an empty conversation, it would be great to have a X or trash icon to simply delete it without having to go through additional steps
- When clicking on the info icon a new column appears on the right, but there is no automatic scrolling, so the user might not see it, depending on the size of her/his display - another option could be to collapse the left column to show only the user avatars when the third column appears, to save space 

I hope the explanation is clear enough. I can upload screenshots and/or a mockup if you need them.

**Comment by Slanfan** [comment]
Hi

Could you specify screen resolution and app zoom level used?

I assume that the info panel is overflowed and thus not visible. The three panels should adjust but of course they have a minimum with as well. 

But if you specify the screen resolution then I can test and it's no problem scrolling the info into view.

**Comment by Slanfan** [comment]
By deleting an empty chat, you mean the Sam function as leave message group under info panel?

**Comment by novalore** [comment]
> Hi
> 
> Could you specify screen resolution and app zoom level used?
1366*768 on 11" Macbook air

**Comment by novalore** [comment]
> By deleting an empty chat, you mean the Sam function as leave message group under info panel?

Yes, the same as the "leave" button. First time I wanted to delete a chat I was looking for an icon near the name (appearing on hover, for example), then I realized that it could be found in the info panel and opened it

**Comment by Slanfan** [comment]
Thanks. I will fix this with a simple solution making the panels less wide to be able to fit into smaller screens.
In addition, I also noticed that the clock setting did not apply to messages and get to fix this as well.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/6dc8a6d84c0f1982d01c4fd1265dcc647715b6ed
