### ISSUE TITLE
Deck pic submitted is shown even though only a list and no pic has been uploaded

### ISSUE THREAD

**Issue by fvonbredow** [Slanfan/MTG-Tolaria#183]
see attached screenshot. if only a decklist is submitted, the colour of the deckpic icon will not change, but hover over info says a pic is submitted.
![deckpic and list bug](https://user-images.githubusercontent.com/69508769/109633200-209db400-7b48-11eb-9976-47f9cd2b6f6e.jpg)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/bd57e5836856f692a8b57463514ae412a843e5da
