### ISSUE TITLE
Opponent's screen goes black

### ISSUE THREAD

**Issue by ztrawhcsj** [Slanfan/MTG-Tolaria#184]
I got my first few matches played on Tolaria tonight. Everything was great. Just one small hiccup kept happening where the opponent's screen would go black and I stopped hearing them on audio as well. The fix was easy as I just refreshed the webpage and everything returned to normal. One opponent mentioned that my screen had gone black as well at the same time. It happened once per match with each opponent. (three times total, about once in every 40 minute match).

**Comment by Slanfan** [comment]
This should now be fixed.

https://github.com/Slanfan/Tolaria/commit/2d03ae3097daacff7f028ed8ee657d15894eec48
