### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by d0314** [Slanfan/MTG-Tolaria#189]
I am seeing two different times on the Event Information page. Which also does not match the zone in my settings.

![n00bc0mtime](https://user-images.githubusercontent.com/81771731/113335165-78ccff00-931c-11eb-9844-516c1b53891f.jpg)
![noobcomtime](https://user-images.githubusercontent.com/81771731/113335189-7e2a4980-931c-11eb-9c85-4c982b424e9d.png)

**Comment by Slanfan** [comment]
This is really weird.
![image](https://user-images.githubusercontent.com/9950323/113339468-c81a2c00-932a-11eb-9f42-7b521b0e2876.png)

I have Stockholm selected and it has the exact same settings as Amsterdam. Does this make any sense to you @JonnieHedkvist?

`{
      countryCode: 'SE',
      countryName: 'Sweden',
      olson: 'Europe/Stockholm',
      UTC: '+01:00',
      DST: '+02:00',
      zoneCode: 'CET/CEST',
      zoneName: 'Central European Time'
 }`

`{
      countryCode: 'NL',
      countryName: 'Netherlands',
      olson: 'Europe/Amsterdam',
      UTC: '+01:00',
      DST: '+02:00',
      zoneCode: 'CET/CEST',
      zoneName: 'Central European Time'
}`

**Comment by Slanfan** [comment]
This has to do with DST (Daylight Savings) and the fact that we turned into UTC +2 in the shift of April.
This should also be solved since I changed how the UTC TimeZoneOffset is stored. 
On every login, the device UTC settings is pushed as the timezone offset now.
