### ISSUE TITLE
Real time standings+ sorted tables

### ISSUE THREAD

**Issue by dthird3** [Slanfan/MTG-Tolaria#192]
Make real time standings and sort the tables so we can see “top tables”

**Comment by Slanfan** [comment]
What do you exactly mean by "real-time standings"?
We can of course calculate the standings whenever a result comes in but it's always up to the TO if they want to show the standings or not at all times.
For swiss events, the default behavior is to show the standings prior to the last round.

The pairings are now sorted by **table number** but with YOUR table as a floating row at the top for easy access.

**Comment by dthird3** [comment]
I think it would be good to have a table similar to what gets printed out at real tournaments... like an extra tab at the top alongside the round tabs. Something like this:

![B782F529-4C3B-4466-8F17-86486A66B2B9](https://user-images.githubusercontent.com/16740071/113511664-ef414b00-952e-11eb-95fe-d779b5d8770c.jpeg)

I don’t think any TO would want to hide the standings... in the current setup you can work it out but it’s a pain to do it. Way easier to check who is making the cut with a leaderboard like this than to look at the records of each player at the top tables.

**Comment by Slanfan** [comment]
As said. Standings are present prior to the last round for everyone. TO's have the standings all the time. 

Usually at tournaments standings will not be posted until after the next last round (aka prior to last round) and Tolaria defaults to the same behavior.

**Comment by dthird3** [comment]
Yeah, I don’t see a reason you would want to hide it. The information is available, I’m just suggesting you make it easier to figure it out. Normally it’s only posted at certain points at tournaments to save paper and because they don’t have the ability to track it in real time.

**Comment by Slanfan** [comment]
I will make it an option for the TO to show the standings if they want. The standings will only be calculated at round end anyways for Swiss so I don't really see the point showing it other than close to the playoffs. 

But it will be up to the to to chose.

**Comment by sebcelia** [comment]
current time round time remaining in the standings/round section would be nice also since there is where you usually check in waiting for the next round in one day tournamenst
