### ISSUE TITLE
Player Indicators in Feature Match Interface

### ISSUE THREAD

**Issue by gordonandersson** [Slanfan/MTG-Tolaria#211]
Sometimes a player has problem with joining the feature match but they are in the Tolaria room. Would be great with just a small indicator that shows if the player are in Tolaria because then one can reach out if the Feature MAtch things doesn't seem to work.

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/126084119-9579422a-011a-40d2-83f5-76f552a2bd17.png)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/520bd17b9c9aa3a842d76a6ab9c5c19a23a71487
