### ISSUE TITLE
Downloadable Standings

### ISSUE THREAD

**Issue by gordonandersson** [Slanfan/MTG-Tolaria#212]
After an event is done iw would be cool to be able to download a txt witgh final standings. With top8 matches as well if possible.

**Comment by Slanfan** [comment]
@gordonandersson  could you please specify how this file should look?
Maybe add a mockup file from an event as a template for me to use.

**Comment by gordonandersson** [comment]
Would mostly love a CSV like this:
Standing (Swiss), Player, Deck Name, Points, Top8/Top4/1st/2nd

Last part there is one more column with info where they ended up in top8. I believe those options are enough.
