### ISSUE TITLE
Tolaria website crashs, when i change Player and Games per Group

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#214]
<img width="1256" alt="Bildschirmfoto 2021-04-18 um 15 32 00" src="https://user-images.githubusercontent.com/77571615/115147477-73312200-a05b-11eb-879b-3caa96638e2d.png">
I changes the first two numbers to 3 and 4, it seems i cant start the tournament because it wants exaclty 4 Players in all Groups? But when i now change the numbers, i cant, tolaria doesnt respond and the website crashs.

**Comment by Slanfan** [comment]
Hi. 

The group with 3 players will not be able to be paired as three players will be able to play three different opponents.

**Comment by Slanfan** [comment]
I'll have to look into the crash thing though. That does not sound good. Might be it causes an infinite ♾ loop in trying to create the groups or something. 

Need to investigate.

**Comment by Slanfan** [comment]
Should be solved with the deploy of commit: https://github.com/Slanfan/Tolaria/commit/0cb70d2afc284c8bbe05a97b787e6a905b067db3
