### ISSUE TITLE
Reprint Policy Drop Down

### ISSUE THREAD

**Issue by Universe-Inc** [Slanfan/MTG-Tolaria#215]
Add 'Special', 'See event' for reprint policy as a catch all for formats with different reprint policies.

**Comment by HW-MTG** [comment]
I would like to see this one as well for the ODOL specials

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/126083847-82656170-d0b0-48ef-a448-17eed9c874e6.png)
