### ISSUE TITLE
Leave group in messages

### ISSUE THREAD

**Issue by HW-MTG** [Slanfan/MTG-Tolaria#218]
I'm able to remove (leave) chats I have 1:1 but i can't remove or leave the message groups of previous tournaments i've joined (e.g. Noobcom2 and Charity battle). It would be great if there is a way to remove these from my messages overview, certainly now there monthlies being hosted and these will pile up.

**Comment by Slanfan** [comment]
You are able to leave if the event has status **ended**. But if the organizer has not ENDED the event the option will not be available.
