### ISSUE TITLE
Missing Scrollbar at "Create Event"

### ISSUE THREAD

**Issue by Tzen** [Slanfan/MTG-Tolaria#219]
On a Windows PC with Chrome I'm missing a scrollbar at the "Create Event" page. The only possibility to get to the bottom to enter the cap, public/private etc is by using tab. A scrollbar would be usefull.

**Comment by Slanfan** [comment]
Hi. 

What resolution are you using? 

Without this I cannot recreate the issue and fix the problem. 


In addition, you can change the apps zoom level under your settings if needed.

**Comment by Tzen** [comment]
1920  * 1080 is my resolution.

I need to zoom-out to 50% in order to see all boxes straight-up.

**Comment by Slanfan** [comment]
Can you take a screenshot please?
The dialog should be scrollable and I'm not certain all fits the screen straight up as it's currently designed but I'm not by my computer atm.

**Comment by Slanfan** [comment]
I don´t know if you have zoomed Tolaria maybe in your browser. This is how it looks for me with 1920x1080 in both 90% (Settings zoom in Tolaria = NOT Browser) and  100%

![tolaria app_events(1920x1080) (1)](https://user-images.githubusercontent.com/9950323/118365846-a1444c00-b59e-11eb-936d-1e4cfca28c07.png)
![tolaria app_events(1920x1080)](https://user-images.githubusercontent.com/9950323/118365847-a3a6a600-b59e-11eb-93da-08ee5d0e1195.png)

**Comment by Tzen** [comment]
This is my screen. Tolaria Settings 90%, Chrome Settings 100%.

![image](https://user-images.githubusercontent.com/3431478/118388014-19a02100-b622-11eb-8e69-05c90e2e112e.png)

**Comment by Slanfan** [comment]
Your resolution does not look like 1920x1080 but anyways, there is a scollbar (hidden) in the dialog and you can scroll it. 

Another thought. Are you on a tablet or some kind?
I have not tested the scroll functionality on tablet device.

**Comment by Slanfan** [comment]
Windows also have a zoom feature for the native os.

**Comment by Tzen** [comment]
It is 1920 * 1080 and was on 125% scale/layout. I've switched it to 100% which makes more things visible but still not everything.

I'm on regular laptop. With tab I can get to every field so it's not a big thing. Unfortunately I can't add video's here so I can show there is no scrollbar, I've tried to click everywhere to unhide it :-)

![image](https://user-images.githubusercontent.com/3431478/118389713-73591900-b62b-11eb-81b8-b9756069f603.png)
![image](https://user-images.githubusercontent.com/3431478/118389736-9257ab00-b62b-11eb-85fd-36bb0673b0e4.png)

**Comment by Slanfan** [comment]
https://user-images.githubusercontent.com/9950323/118391481-cc797a80-b634-11eb-9f7f-711253507629.mp4

**Comment by Slanfan** [comment]
See above for screen recording on my mac 1386x786

**Comment by Tzen** [comment]
Tested it on another laptop with 1920 * 1080. Same thing, no scrollbar and not every field is visible. What makes it a lot easier is that with that laptop I use a mouse with a scroll-wheel, so I can scroll down easily.

What I probably forgot to mention is that on my regular laptop, I don't use a mouse so I don't have a scroll-wheel. Therefor TAB is the only way to get to the other fields. No biggy for most people I guess ;-)

**Comment by Slanfan** [comment]
But you have a trackpad I assume. What kind of pc does not support scrolling on the trackpad? I've never heard of things like that but it wouldn't be the first time either.

**Comment by Slanfan** [comment]
I'm also very confused about the fact that your 1920x1080 has a different sizing than my 1920x1080 

Are you sure you do not have ZOOM level in chrome on Tolaria.app? 
_chrome remembers the site specific zoom level and if you accidentally zoomed once this will be zoomed whenever you visit again._

Reset zoom with **ctrl+0**
Check zoom level in Tolaria settings (user settings) and adjust to 100% and take a screenshot.

**Comment by Tzen** [comment]
First picture is:
1920 * 1080
125% Scale Layout
100% Zoom in Chrome
100% Zoom in Tolaria

![image](https://user-images.githubusercontent.com/3431478/118640445-45193c00-b7d9-11eb-965f-a9c90cdbf798.png)

Second Picture is:
1920 * 1080
100% Scale Layout
100% Zoom in Chrome
100% Zoom in Tolaria

![image](https://user-images.githubusercontent.com/3431478/118640598-72fe8080-b7d9-11eb-8e38-cd645fd59c80.png)

**Comment by Tzen** [comment]
BTW: Scrolling on the trackpad works.... I just never use it as I always look for the scrollbar. I'm a IT guy who sucks with UX (building and using) and point and click everything ;-)

**Comment by Tzen** [comment]
In order to see it all I need to use:
1920 * 1080
100% Scale Layout
67% Zoom in Chrome
100% Zoom in Tolaria

![image](https://user-images.githubusercontent.com/3431478/118640982-e43e3380-b7d9-11eb-8ef0-42e625bf0ed2.png)

**Comment by Slanfan** [comment]
Very strange that the resolution vary that much between the same "resolution". 

With that said. I keep the ticket open and add the visible scrollbar when I have time. ☺️

**Comment by Tzen** [comment]
Haha, no worries. Thanks

If you want me to do more tests with my specific resolution please let me know. Making something work on all resolution/devices is probably 1 of the most annoying parts of UX Design. So it's more than fine to ignore my specific setup ;-)

**Comment by Slanfan** [comment]
@Tzen I have changed the layout of the New Event Form somewhat, can you see how this fits your screen?
PS. Having a hard time adding the scrollbar as the framework I´m using seems to hide it when I open a modal page and I can't get it to be visible again :(
