### ISSUE TITLE
View casual matches, not part of an event.

### ISSUE THREAD

**Issue by Tzen** [Slanfan/MTG-Tolaria#220]
I wasn't able to view Casual matches scheduled between 2 other players, in order to stream a match. Only when a match is part of an event, I can join as a viewer and stream.

I think it would be good if also casual matches can be viewed (maybe by sharing a specific link as I understand you don't want them to appear to everybody), so people can schedule a casual match and stream it.

Maybe I overlooked how to do this. But both Thomas and I couldn't figure it out.

**Comment by Slanfan** [comment]
Hi. 

Sharing the link to the match is enough to let spectators in and watch. 

The only thing one should be aware of is that the features as of today is pure WebRTC peer-2-peer which means that everyone in the "room" calls each other. If two players have 10 spectators they both need to send their stream to 9 other users and this may cause bandwidth issues for the players.

**Comment by Tzen** [comment]
Okay, clear. I was thinking you needed a specific spectator link to avoid certain issues. But if not this is easy to share and stream.

Thanks!

**Comment by Slanfan** [comment]
Duplicate https://github.com/Slanfan/MTG-Tolaria/issues/236
