### ISSUE TITLE
Deck Photo image link broken

### ISSUE THREAD

**Issue by Tzen** [Slanfan/MTG-Tolaria#222]
In the Raging Bull Event when I click on a Deck Photo from players who've uploaded a deckpic already, I get a broken image link for some players. When I checked this yesterday it did still work.

Example players are: Pablo Vera (Chilean Ritual ), Gideon Evers & others

**Comment by Slanfan** [comment]
Are you talking about the DOWNLOAD or the actual deck photo under the player profile in the event?

![image](https://user-images.githubusercontent.com/9950323/119821452-ddf33a00-bef2-11eb-865d-45e1b2f922d2.png)
![image](https://user-images.githubusercontent.com/9950323/119821485-e9466580-bef2-11eb-8ab9-cdce8133d07f.png)

**Comment by Tzen** [comment]
The actual Deck Photo. Before reporting the bug I triple checked everything. Logged in and out and it didn't work. Obviously now it does. You can close the ticket, sorry for bothering you 🙁

________________________________
