### ISSUE TITLE
Path to Victory

### ISSUE THREAD

**Issue by Baldrickus** [Slanfan/MTG-Tolaria#226]
It had been great to see possible ways to the quarter/semi/final during a tournament.
E.g. If you beat A, B loses against C. 
It is possible that this is difficult to code. Just an idea :)

**Comment by Slanfan** [comment]
Hi, please elaborate some more here. Add concrete examples and maybe some images explaining what you would like to see.

**Comment by Baldrickus** [comment]
![image](https://user-images.githubusercontent.com/85223436/122676728-87baa380-d1df-11eb-9430-dbd43f7fa273.png)
 I was thinking when there tournament is n-1 or n-2 matches left you can press a button besides everyones name. 
 If you hare sure to qualify the button should say samething like QF (Qualify) or a crown or someting. If you can QF it could bee a question mark or something. If you press the question mark. It opens a window.

The Window says something like this:
**PATH 1:**
A needs to beat B 2-0 or better
C needs one game win
F needs to loose all games
**PATH 2:**
You must win your match 2-0
**PATH 3**:
You must win your match 2-1 and F needs to Win no games

I think this is possible to do with N-1 matches left. Not sure about N-2.
The QF could be easier to calculate but the path to victory is more tricky.

**Comment by Slanfan** [comment]
Yeah. This needs some tinkering.
