### ISSUE TITLE
Match Actions Log in the Game Chat

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#228]
I like the animation and the stuff, but i think it would also be good, if the result of a coin flip or dice roll will be visible in the game chat.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/132e87216941e62663a850e73c4221a246b9b184

**Comment by Slanfan** [comment]
Actions are now saved as messages as well

![image](https://user-images.githubusercontent.com/9950323/126219843-4126918e-2cd1-4a6e-bde7-997e6f556171.png)
