### ISSUE TITLE
Match results not in line with reports

### ISSUE THREAD

**Issue by HW-MTG** [Slanfan/MTG-Tolaria#238]
I have a couple of matches this month where the report slip states 2-1 but in the group it shows up as 2-0. I've added screenshots, I don't have the match ID but this match was played in Group D of the July ODOL
![Screenshot 2021-07-12 at 10 14 54](https://user-images.githubusercontent.com/83812531/125254505-cdf4b580-e2fa-11eb-9c6a-d8956502262a.png)
![Screenshot 2021-07-12 at 10 14 33](https://user-images.githubusercontent.com/83812531/125254523-d4832d00-e2fa-11eb-82c9-4ed9175647bc.png)

**Comment by Slanfan** [comment]
Found the issue. Checked my report slip and the document. The [Add/Remove] game wins only updates the wins for the player using it, it should also update the losses for the opponent which was not the case. This is about to be fixed.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/132e87216941e62663a850e73c4221a246b9b184
