### ISSUE TITLE
Scheduling availability

### ISSUE THREAD

**Issue by sebcelia** [Slanfan/MTG-Tolaria#247]
Add a scheduling avaliability button when hovering over an event in the event section.

**Comment by Slanfan** [comment]
Can you please make a mockup of this?
Availability is general for all of Tolaria and any event or casual matches etc.

I could add a button for availability in the header of the events section.

![image](https://user-images.githubusercontent.com/9950323/129633908-fc80c1a8-96be-44ca-99f6-b27fd132f765.png)
