### ISSUE TITLE
"Hero" symbol in the match flickers in and out

### ISSUE THREAD

**Issue by sebcelia** [Slanfan/MTG-Tolaria#251]
I played Florian and Fluffy had the same problem. The Hero icon kept dissapearing and coming back.

**Comment by Slanfan** [comment]
It's not really disappearing. Or it does but it toggles between the hero badge and clubs. If the player is not in a club it will looks like it disappears. Good to have a ticket on this now so that I remember to fix this. 😎

**Comment by Slanfan** [comment]
I will keep this as an improvement as I need to remake the component that toggles the badges.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/26befedfc6f817edd62d149a56566f06f2ff432b
