### ISSUE TITLE
Player information - extra field for secondary method of communication

### ISSUE THREAD

**Issue by lcpdenijs** [Slanfan/MTG-Tolaria#254]
I think it would be very helpful is there was an extra field added to the player information where you could add a secondary method of getting in touch, e.g. a FaceBook handle.
A lot of users have a FB account and if a player doesnt respond quickly enough via Tolaria you could contact him via FB (or whatever other option the player submitted)

**Comment by Slanfan** [comment]
I have this on the roadmap but don't think I have a registered issue for it. Now we have. 😜

**Comment by lcpdenijs** [comment]
Great!

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/64b5cddf3c0772c27b2df0c77b89671a0e5da6e0

**Comment by Slanfan** [comment]
![Tolaria-1 2 7](https://user-images.githubusercontent.com/9950323/130744484-2de91236-d4a9-40e2-8e52-e1e7f854df20.gif)
