### ISSUE TITLE
Player information - extra field for guild information

### ISSUE THREAD

**Issue by lcpdenijs** [Slanfan/MTG-Tolaria#255]
I think it would be fun to have an extra field so that players could enter their guild.
This way, you would be able to filter on guilds, see how guild perform, etc.

**Comment by Slanfan** [comment]
I think clubs should be used for this as I have already built a solution to list clubs, manage clubs and so on. 

It would be easier to implement some kind of performance per club. But it would be nice to see some kind of mock-ups and thought on how this could be used.

**Comment by lcpdenijs** [comment]
What I meant to say is that it should be nice and handy to see what Club a player belongs to.
When you look at players now, you don't see to which club they belong.
And also, when you click on a club you don't get to see a list of their members.

**Comment by lcpdenijs** [comment]
One more suggestion, clubs are now a bit "hidden". You have to go to players, the on the top right you can find the clubs section.
Wouldn't it be a good idea to make a seperate button for clubs on the lift side of the menu below players?
That way I am sure it will be used more since you constantly see it and are reminded of it.
![image](https://user-images.githubusercontent.com/89067536/129896721-d844b3c5-d989-45db-9d59-2d356474db42.png)

**Comment by Slanfan** [comment]
![MTG-Tolaria-issue-255](https://user-images.githubusercontent.com/9950323/130702709-e63e9ce5-0bff-46d7-b43e-9c185eddb4f0.gif)
