### ISSUE TITLE
Report slip options

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#256]
Currently, you only have the option to draw (0-0 or 1-1) and to win (2-0, 2-1 or 1-0).
Would it be possible for a TO to remove or add certain options? It could be that a TO wants other options (so no option to draw 1-1, or best-of-5).

**Comment by Slanfan** [comment]
I thought about this at an early stage but went without it as it might be just corner cases when used. 

Re-building the solution for this would most likely be more than I would like to. But I need to consider it.
