### ISSUE TITLE
TO panel -> Deck Submission reminder

### ISSUE THREAD

**Issue by lcpdenijs** [Slanfan/MTG-Tolaria#261]
When I want to send all players who didn't submit a deck picture, the message seems to be send twice.
Offcourse I can edit the message,but after that it crops the text (see pic)

![image](https://user-images.githubusercontent.com/89067536/129687115-3eaacbf1-3d2d-4150-a8b2-44720164a872.png)

**Comment by Slanfan** [comment]
Is this a message sent from the Deck Submission interface or from a regular chat message?

**Comment by lcpdenijs** [comment]
This is a message that is automatically send from the Deck Submission Interface when you send a reminder to people that havent submitted a deck pic

**Comment by Slanfan** [comment]
I only see one message. DO note though that the message contains a list for missing:

- Deck Photo
- Deck List

Aka, there are two lists if your event has both Deck Photo and Deck List enabled.

**Comment by lcpdenijs** [comment]
you are right about this. I tried it again with only the deck pic option and it works!
