### ISSUE TITLE
Group play w Teams

### ISSUE THREAD

**Issue by B75-Simon** [Slanfan/MTG-Tolaria#262]
Hi Slanfan

We have a monthly Tron Wars tournament, and would love to use Tolaria. 

Im not sure if you already do this, but we in denmark play 8 groups and the two best from each group go to a top16, normally we are around 50-60 players, and we divide them into 8 groups both by a toplist(8 best seeded players go one each to the 8 groups) and also spread the teams out in all the 8 groups, is that possible to do on Tolaria? 

The reason i want to use Tolaria is of course the registraton and top8/16 tools. as well as the gameplay.

Now each month top8 gets points for the toplist, 5-4-3-2-1-1-1-1.

So my question is if its doable, and "easy" to do? i could also do the math in excel and then maybe make changes to the groups, like a "not live" pairing and then fix the seedings, and go live with it?

Let me know if you have more questions? 

regards

Simon

**Comment by Slanfan** [comment]
Let's book a session where we can talk. Send me a match invitation and book that with a match appointment according to my availability and we figure it out with a talk. Think I need some information and might have questions that easily can be misinterpreted in writing.

**Comment by Slanfan** [comment]
This should be feasible with the "new" Leagues section I believe
