### ISSUE TITLE
Add event name when downloading deckpics

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#263]
When you download deckpics now I only see the name of the player as name for the textfile.
It would be great that also the event name would be added.

![image](https://user-images.githubusercontent.com/89067536/130638519-6885fa00-9251-4a66-a6fe-8c1ebb37c8be.png)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/b724cd7e0695160ff4f84e90960bf85bc19ccacd
