### ISSUE TITLE
Player info - add handle information (like Facebook handle)

### ISSUE THREAD

**Issue by lcpdenijs** [Slanfan/MTG-Tolaria#266]
Almost everywhere you see the playover popover with the handle information people enter (see SS below)
![image](https://user-images.githubusercontent.com/89067536/130771184-ed9085ca-8501-454c-809d-ac974f8af622.png)

This extra handle info isn't shown yet in the players menu yet(see SS below)
![image](https://user-images.githubusercontent.com/89067536/130771128-60e9df27-5fb3-4f6f-b567-fb3108cddddd.png)

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/130786267-327f0cf9-8358-40ae-bd36-955c8a67eb34.png)

**Comment by lcpdenijs** [comment]
Sweet!
Perhaps you could even add a email option (I know email adress is listed somewhere else), but I think this is the quickest way.
So next to all the current handle options, also add the e-mail handle so that can be chosend if desired.

BTW, if I enter my Whatsapp handle and mobile number, when I click on that handle it doesnt show the mobile number what I use for WhatsApp but goes straight to the Tolaria website

![image](https://user-images.githubusercontent.com/89067536/130792720-88f42664-b333-47ad-8735-c53bb7bd4d2d.png)
