### ISSUE TITLE
Extra information field with player info

### ISSUE THREAD

**Issue by lcpdenijs** [Slanfan/MTG-Tolaria#268]
Is it possible to add an extra field where you can put important information, like that you are on leave for a couple of days, or other stuff (one guy I know has always issues with the playroom, so he want to play on whereby) This way they could put a message like that there so its clear for everyone.

See example below:

![image](https://user-images.githubusercontent.com/89067536/130915294-973d1e93-89cf-4cce-bd60-ac0adf7d1a46.png)

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/136102086-93971fe8-08a6-45a7-ade1-ccc9920c67aa.png)

**Comment by Slanfan** [comment]
C:\Users\MattiasBerggren\Desktop\2021-10-05 23_02_46-Tolaria.png

**Comment by Slanfan** [comment]
Release with Sprint 10

**Comment by Slanfan** [comment]
e0daf3a91c6386e85056496ce3a04a18ecf29f14
