### ISSUE TITLE
Players can see other players deck lists and photos

### ISSUE THREAD

**Issue by antonbglans** [Slanfan/MTG-Tolaria#275]
Hi!

I'm organizing the Tolaria Open - Premodern on September 4th in Tolaria. I have chosen to not check the "Deck photos and Lists public for all players", still a player commented in the Tournament chat that he could see deck lists and photos of those submitted. I don't know how to fix this. Can you help me ASAP?

Regards, Anton

![Tolaria Open](https://user-images.githubusercontent.com/89859458/131531483-8c6adc86-5a43-4131-8ae2-45e2225098d9.PNG)

**Comment by antonbglans** [comment]
Apparently, other users can also choose to unattend other players?!

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/d9d16a69eda7c7d283daad9d6c9aafb8d65f0a28
