### ISSUE TITLE
Same pairings happening in successive rounds

### ISSUE THREAD

**Issue by cdevos** [Slanfan/MTG-Tolaria#278]
Hi @Slanfan,

I played yesterday (4 Sep) in the ForestFrenzy tournament (live), Mitja handling the pairings with Tolaria.app.
It is great that live tournaments can also be handled, as I could see the top 8 bracket results when I was back home.

But to the point. In round one, I played Simon and we drew (no time for game 3).
We were paired against each other at least 3 times in the following rounds, which had to be manually fixed by changing the pairings; this was a real headache for Mitja (because I believe he tried to repair us with other players with a draw, but we had already played each other in the last round and got me the bye, while I was not the player with the least points I believe.

I have not seen this reported in the opened bugs, so could you please look into it?

Thanks for the great software.

Cheers,

-- 
Carl

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/220/commits/8b00e0ce19f3d746ff2cd64b6cb5dcab0004b9e3
