### ISSUE TITLE
Mail when a tournament starts

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#285]
Since a lot of Tolaria users don't check on Tolaria regularly, I notice that a lot of players "forget" when a tournament starts.
Would it be an idea to send out a mail when a tournament starts, just like they get a mail when there is a match proposal?
This way, everybody who attends a tournament will be notified thats it started and that they have to do something to start planning the matches.

**Comment by lcpdenijs** [comment]
Also, it might be a good idea to make sure announcements are also send via email as an extra reminder.
Like e.g. when I want to remind players that there is just 1 more week to play, or that we still need decklists, etc.

**Comment by Slanfan** [comment]
Should be solved already, email reminders will be sent 7 days ahead of time and 24 hours ahead of time.
In addition, there's now possible (when I deploy payment) to send announcements both as Tolaria Message and/or Email.
