### ISSUE TITLE
add email handle

### ISSUE THREAD

**Issue by lcpdenijs** [Slanfan/MTG-Tolaria#290]
Currently, you can't add an e-mail as an extra handle so there is no way of reaching out to a player that doesnt respond via Tolaria (and isn't on FB)

![image](https://user-images.githubusercontent.com/89067536/134631787-0e0c76f3-429f-41d0-a246-64c0b8d42b35.png)

It would be nice to be able to add that as an extra handle, just like you can add different extra handles (see pic above)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/201/commits/85485192b283bbee47905020572b6e10b9a7c0a0

**Comment by Slanfan** [comment]
Will be deployed with release of Sprint 10

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/020afbbfa4b609b5e3a13ec9bca69efde87a14e4
