### ISSUE TITLE
"Add player to a group paired against all players" - option

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#294]
When a player is dropped from a group you can't add another player to that group later on.
You either have to just drop a player (and have a player less in that group) or immediately exchange a player for another player (which is not always possible if you don't have a replacement)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/201/commits/27d556d87bcd37a2e2b210d99d8037306ba26006
