### ISSUE TITLE
Standings by Group

### ISSUE THREAD

**Issue by Razor22Razor** [Slanfan/MTG-Tolaria#295]
It would be great to be able to sort ongoing tournament results by group.  

eg. Group B, Group H, whichever

During the Group stage before Top 8 or Top 16, all each player cares about is how we're doing in our specific pods.

Regards,

Raymond Mitchell

**Comment by Slanfan** [comment]
Hi. You are able to filter on group by entering the group letter like this. 

Group A

That will show the standings for group A only in the standings list.

**Comment by Razor22Razor** [comment]
I was able to type Group B into the search field to see standings, thanks
