### ISSUE TITLE
Life total needs to be manually reset upon game start

### ISSUE THREAD

**Issue by sebcelia** [Slanfan/MTG-Tolaria#299]
"NAN" comes up and life don't show when entering the room in the X-point league. Needed to reset life to get it back. The problem did not occur if you had reset your life and re-entered the room.

My opponent had the same problem one time earlier also.

**Comment by Slanfan** [comment]
Do you have the match id of this match?
Can be copied from the matches section with the copy id button.
![image](https://user-images.githubusercontent.com/9950323/135932200-bff73ee8-af66-4c91-9eea-df1b357dfee5.png)

**Comment by Slanfan** [comment]
@Slanfan this might be due to manual pairings or changes done to matches by the TO.

**Comment by sebcelia** [comment]
bd5938cd-cb9a-47a7-be15-46039124bb29 Match ID

My opponent was added to the group after one player dropped. Could be at
his end/when he was added it happened, yes.

//Seb.

Den tis 5 okt. 2021 kl 00:18 skrev Slanfan ***@***.***>:

**Comment by Slanfan** [comment]
I do believe this is solved.
