### ISSUE TITLE
Decklist or -pic reminder message for dropped player

### ISSUE THREAD

**Issue by lcpdenijs** [Slanfan/MTG-Tolaria#300]
Dropped players get mentioned in the message regarding missing decklist and/or -pics.
(In the example below, Andrew Landeen was dropped)

![image](https://user-images.githubusercontent.com/89067536/135857301-a54ea0b9-ae49-4046-92c5-518447d3d63c.png)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/526887a69194a0606992c3fe19ae582e67264d88
