### ISSUE TITLE
Leagues - cumstom points to be show with point structure

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#304]
Is it possible to have custom points for leagues (see ss below where I added some customs points in the league information field) shown with the regular points structure?

![image](https://user-images.githubusercontent.com/89067536/136357840-9b846101-35b4-462b-b0ac-6ef7b745be1a.png)

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/154151648-79e574d9-4e77-471e-ac96-7f8d0acde6e1.png)
![image](https://user-images.githubusercontent.com/9950323/154151701-b3d71ada-de19-4dab-8250-eadc01280cb0.png)
![image](https://user-images.githubusercontent.com/9950323/154151718-9d510035-9f08-4d29-802a-8f4fa7d54a09.png)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/221/commits/67d50d110fa2fda2deea475cf96d99289430a426
