### ISSUE TITLE
Scheduling an appointment

### ISSUE THREAD

**Issue by k4b4l74** [Slanfan/MTG-Tolaria#318]
The first popup of the opponent is always in "front" so i can't use or see the second one

See this pictures: https://i.imgur.com/gZIFYTE.png

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/147610881-c1449e7f-497b-48df-9796-86b2278cf4e8.png)

**Comment by Slanfan** [comment]
Will be fixed when deploy of commit https://github.com/Slanfan/Tolaria/pull/216/commits/4172f79b2dd3bc21b70ebfc0c736acf4ca77faf3 will be merged into the production environment.
