### ISSUE TITLE
Tolaria - Deck Builder app: Missing cards

### ISSUE THREAD

**Issue by BeastieBas** [Slanfan/MTG-Tolaria#323]
Hi Slanfan, I noticed some other cards are missing in the Deck Builder app, namely the Legendary Creature cards of Legends as I was trying to add "Sol'Kanar" to my deck but could not find him, nor other Legend.

Best regards,

Bas

**Comment by Slanfan** [comment]
This should be fixed since I moved all card search to Scryfall
