### ISSUE TITLE
Trouble clearing old matches

### ISSUE THREAD

**Issue by Razor22Razor** [Slanfan/MTG-Tolaria#324]
Clicking red delete button on old matches from old tournaments that have ended does nothing.

![image](https://user-images.githubusercontent.com/91067529/138101613-7fbfe0bd-f440-4c19-9374-3667495f52dc.png)

**Comment by Slanfan** [comment]
Yeah. I should most likely remove this button as you should not be able to delete matches from events. The button is disabled and that's why nothing is happening when you press it.

**Comment by Slanfan** [comment]
I believe this is fixed since we removed all matches from Xpts #8
