### ISSUE TITLE
Latest Brews

### ISSUE THREAD

**Issue by BeastieBas** [Slanfan/MTG-Tolaria#329]
I noticed that now the latest brews are shown on the opening page, is there any possibility to lock your deck from being visible when you are still playing a tournament with that deck? As it seems now all new brewed decks are listed there and everyone can see these, so you might see decks of your opponents you are playing in a tournament as Xpts and ODOL. For example I noticed that there was a deck from DFB which was noted to be "DFB Xpts Nov  10pts WW" and this tournament still has to start on the 15th of November.

I see now the "Private" button is working now, so if we would activate this, the deck would not shown to everyone on Tolaria, correct?
It might be good to inform everyone of this or the Tournament organizers as otherwise all decks will be visible too early.

Best regards,

Beastiebas.

**Comment by Slanfan** [comment]
#332
