### ISSUE TITLE
Latest brews showing deckpics and - lists

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#332]
It seems that everyone can see the deckpics and -lists on the latest brews section.
Perhaps it's best that all this information, especially when a deck is played in a tournament that is live, are set to private.

**Comment by LoekieMtg** [comment]
One more remark about latest brews, it's now so that when a deck is used in a tournament that is ongoing, you can't see that deck.
But you still see the deckpics and -name, so you have a clue what that player is playing.
I think a deck that is used in a tournament should by default not even be listed in latest brews, even if the player didn't set it to private.
When the tournament is over, it's fine that it will be shown in latest brews. If the player doesn;t want that, he can also set it to private.

![image](https://user-images.githubusercontent.com/89067536/143393964-758d43c6-d9d7-4c26-affc-e28f92067852.png)

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/221/commits/da0a4823f852d7caca525dbdb28ae50236ed4757
