### ISSUE TITLE
Deck Builder - Missing cards

### ISSUE THREAD

**Issue by BeastieBas** [Slanfan/MTG-Tolaria#333]
I tried to search for Dark Heart of the Wood but it was not listed in the Deck Builder;

For the Scryings Invitational I tried to find these cards in the Deck Builder, but I could not find "Tithe" for example, is the Deck Builder still limited to the 4H's sets and FE?

Cheers,

Bas.

**Comment by LoekieMtg** [comment]
Looks like multicoloured cards are missing, can't find Scarewood Goblins either

**Comment by Slanfan** [comment]
Should be fixed now since I have changed the card search to look at cards from Scryfall
