### ISSUE TITLE
Match Appointment Reminder misses localized timezone

### ISSUE THREAD

**Issue by thommyslaw** [Slanfan/MTG-Tolaria#334]
As a player I want the mails sent for match appointment reminder to show my personal / localized timezone. 

Currently the reminders always show the timezone GMT.

**Comment by thommyslaw** [comment]
Unfortunately I wasn’t allowed to label the issue. Should be a minor bug.

**Comment by Slanfan** [comment]
Should be fixed now. The time zone should be local AND also GMT/UTC0

Both the emails were produced the same so both players got the same email stating hello "creator of the appointment" instead of hello "player receiving the email".

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/216/commits/da62eb74a20d94204b36c475aad83c9fffc179bd
