### ISSUE TITLE
TO option: mark match as unplayed

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#336]
When the group stage of an event is done, there are often a couple of matches left unplayed.
Now you either have to drop that player (also impacting the other matches that he did play) or give them a result (win, los of draw) which is not always the right option.
It would be great if there was an option to mark these matches as unplayed so they arent calculated into the stats and you can proceed with the playoffs.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/229
