### ISSUE TITLE
Unable to click the "attend" button when opening an event. 

### ISSUE THREAD

**Issue by HW-MTG** [Slanfan/MTG-Tolaria#339]
When you are on the main Events page you can see all events and when you hoover over it will allow you to click the attend button. When you click the event to read the information you can't click the attend button. This is also the only way on the mobile interface to click attend, so registering for an event doesn't work on mobile. see the screen below for clarification. 

This used to work in the past so I think it got lost during one of the updates. 
![Screenshot 2021-12-22 at 09 41 33](https://user-images.githubusercontent.com/83812531/147065676-4dd9a67f-c595-49db-aafb-6a4b4f960a57.png)

**Comment by Slanfan** [comment]
Will be fixed when I deploy https://github.com/Slanfan/Tolaria/pull/216/commits/94980218851d10190b03382e9ad037d1d2418251
