### ISSUE TITLE
Maintain peer connections locally

### ISSUE THREAD

**Issue by Slanfan** [Slanfan/MTG-Tolaria#34]
All peer connections need to be maintained locally and not within the peer itself to be able to handle disconnection and such events.

**Comment by JonnieHedkvist** [comment]
Closed bc of peer webrtc doesn't handle the firing of MediaCOnnection events well on the reviever end, we therefore have no use for this since we can't reliably tell when a peer has 'closed' a call.
See issue: https://github.com/peers/peerjs/issues/752

**Comment by Slanfan** [comment]
Can't we hook something to the "user left the room" which will trigger when they close the tab and the database connection is lost?

**Comment by Slanfan** [comment]
Should have been solved in the event room refactoring
