### ISSUE TITLE
Discontinue email address exposure

### ISSUE THREAD

**Issue by tjirab** [Slanfan/MTG-Tolaria#343]
Greetings! First of all: thanks for your work on Tolaria. Just discovered it and I think it's awesome what you have built so far.

I would like to propose to discontinue exposing email addresses from players' profiles. It was my understanding that the email address was only used for sign up but it turns out everyone can see my email address. Perhaps I am mistaken, but I couldn't find a way to hide the email address in profile settings.

Below an example (redacted):
<img width="411" alt="Screenshot 2022-02-17 at 20 56 06" src="https://user-images.githubusercontent.com/10810907/154560656-28b8cc1f-8143-4775-8f8f-297cfb015e59.png">

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/240/commits/b941304149ff508f1561b650dc75091939e61144

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/194651059-9bf75d3f-fc1a-4913-91a8-41fbb7fa3f56.png)

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/194651242-a2ad7ead-90b2-4dcc-bbb5-36fae1361090.png)
