### ISSUE TITLE
[UX] Deck builder: autoselect the newly generated version

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#352]
When you click on "generate new version", enter the name and confirm, then the new version is not selected. You are brought back to the original.
It would be easier for the user to be directly able to edit the new version just generated.

**Comment by Slanfan** [comment]
Implemented by [1a4f401](https://github.com/Slanfan/Tolaria/pull/239/commits/1a4f401e4dc831dbacfc7d0721f1aca744c4ad3c)
