### ISSUE TITLE
Deck list export title and filename

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#354]
When the user generates a new version of a deck, he/she has to name it. When exporting that version in txt the deck will be titled only with the version name, not including any reference to the original name.
I would prefer to have the original title included in the filename.

Example of desired functionality:
I create a deck named "UR burn" and export the "origin version" --> filename "UR burn.txt"
I create a new version of the deck named "aggro version" and export it --> filename "UR burn_aggro version.txt"
I create yet another version of the deck named "Fishliver top16" and export it --> filename "UR burn_Fishliver top16"

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/239/commits/f46f56edd15d1eb6512b168366e0229d3100c6e4

**Comment by Slanfan** [comment]
The downloaded file will be named `<ORIGIN-NAME> version <VERSION-NAME>.txt`
