### ISSUE TITLE
typo: Registration Fee modal window

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#355]
<img width="359" alt="Screenshot 2022-04-04 at 10 45 10" src="https://user-images.githubusercontent.com/1128726/161507805-f4a5d25c-3772-4431-865b-63ee8d87a7cf.png">
"Registraion" instead of "Registration"

**Comment by Slanfan** [comment]
Will be released together with https://github.com/Slanfan/Tolaria/pull/230
