### ISSUE TITLE
Manually adjust round timer

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#357]
It would be sweet for a TO to be able to adjust the round timer manually, e.g. because you forgot to click on start round after pairings and/or because I had to manyally fix something which caused the round timer to reset (which I didn't want since we were already 10 minutes in a tournament)

**Comment by Universe-Inc** [comment]
I would like to second the manual control of the timer. It would also be great to see that timer inside the event interface counting down both for us as a TO and for players if possible.

**Comment by Slanfan** [comment]
The round timer is visible for all users in the event lobby and in the matches for online Swiss style events. 

For Group events and such it does not make much sense however. 

I'll look into a possibility to manually change the ENDING TIME of a round or have the option to opt out from resetting the round timer.
