### ISSUE TITLE
Force EN language on interface

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#359]
Some devices (Iphones for example) display the interface of Tolaria with automatic translation and it's awful.
The pages should explicitly include the lang="en" attribute to avoid this issue.

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/166802744-61870bf0-07d8-4cdb-b641-34e405a8e848.png)
Not sure if it's on the device side then because of Tolaria.app has always been <HTML lang="en">

**Comment by Slanfan** [comment]
Re-open if you have some more info about device and settings that override this.
