### ISSUE TITLE
Don't always see the matches in the matches section

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#364]
When I want to get back to the matches section after I have visited another section I dont see any matches anymore in Tolaria.
Relogging helps but then again, once you have seen it and visit another section and come back they are gone again.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/237/commits/1a57174d96bddc0fa97bf9e4e0be63ef8266c6a6
