### ISSUE TITLE
typo: maybes column in deck visual spoiler

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#365]
*Maybes* is spelled "Mabies"
<img width="228" alt="Screenshot 2022-05-19 at 12 25 20" src="https://user-images.githubusercontent.com/1128726/169272801-23bd7e33-f67f-4662-811f-17f07bb8052a.png">

**Comment by Slanfan** [comment]
Will be released with https://github.com/Slanfan/Tolaria/pull/230
