### ISSUE TITLE
Video elements resizing

### ISSUE THREAD

**Issue by Slanfan** [Slanfan/MTG-Tolaria#38]
When the stream is loaded into the video elements it resizes and the content becomes hard to watch.

![tolaria-spectate](https://user-images.githubusercontent.com/9950323/101269285-d46fed00-376d-11eb-8b25-a86ca8e9e7d9.gif)

**Comment by JonnieHedkvist** [comment]
Is this in spectator view only? Can't replicate on local stream in my own match

**Comment by Slanfan** [comment]
Yes. Spectator view only.

**Comment by Slanfan** [comment]
Deploying a version of a fix with 0.7.4b and we have to see how it pans out.

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/81614fc08f93b4a9abfeb68f350096fc612fc85f

**Comment by Slanfan** [comment]
Closing now, we can re-open at a later stage if this is not a sufficient solution.
