### ISSUE TITLE
Direct link to deck list/photo in playoff pairings

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#381]
For coverage and deck checks it would be extremely useful to have a direct link ( 📷 ) next to the player name to easily access their decks.

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/192600544-3a52a2d3-61bb-487a-b6bc-5fb733032e3f.png)

**Comment by Slanfan** [comment]
[afa6715](https://github.com/Slanfan/Tolaria/pull/239/commits/afa67151bc79703649c448f1bb8ef4edec2c4e8a)
