### ISSUE TITLE
Droppers from Groups change the standings

### ISSUE THREAD

**Issue by albertberg** [Slanfan/MTG-Tolaria#391]
If a player drops after or during a group phase, the points are reduced for all other players in the group. 

We had 3 groups of  5 people each. 
In the first group two players dropped after loosing all games. 
The best remaining player only has 6 points now instead of 12, which is a disadvantage against other groups.

It would be nice to have an option to either keep the points, or select that every player in a group get's an autowin if a player drops.

**Comment by Slanfan** [comment]
Just out of curiosity. When you say **_"a player dropped"_** you mean that you as a TO dropped the player?
_(Players should not be able to drop themselves, if that was the case I need more information to dig deeper and see if something is wrong in the code)_

I would advice to NEVER drop a player from a Group Event if they have played any matches. Instead I would mark all other matches as INACTIVE. That way you keep the results from the played matches and do not get funky results. 

Would it be sufficient to add this information as a text to guide you and other TO's when performing the drop action on a player?

**Comment by albertberg** [comment]
It happened in the "Elfvalley Cup XIII". Not my tournament. 
You are right players cannot drop on their own. 
Maybe they just selected "unattend Event"?

Probably a Tournament Organizer Guide would be sufficent. 
A lot of stuff is self explanatory, but there are some tricks that are good to know. 
For example if a wrong result was entered two rounds ago and you want to change but still keep the results of the rounds that followed afterwards.

**Comment by Slanfan** [comment]
This issue is implemented by #374 released with the September 2022 release

**Comment by Slanfan** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/9950323/192624241-26c054d5-3058-4bdb-a80a-0d21b93dfc21.png">
![image](https://user-images.githubusercontent.com/9950323/192624504-90045850-6929-426a-8b71-baea8eb3a7c4.png)

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/192624560-24d347a1-5e46-4857-9847-06e7cfab3ac2.png)
