### ISSUE TITLE
Matches from a two year old tournament doesn't disappear from matches

### ISSUE THREAD

**Issue by aginamist** [Slanfan/MTG-Tolaria#392]
This match doesn't disappear from the matches tab and I can't get it reported: https://tolaria.app/match-room/15acc8b5-d7dc-4750-93eb-eb4c092b7482/dab4e592-f938-449f-b712-09dcd9e9f4e6/a4471495-b47d-47e6-a405-d58e081ce846/21cfbb74-d5c3-4f13-b3b0-212704d35d5f/PGc2pOjpufQZv0A4PM4Fked2Dwr1

**Comment by Slanfan** [comment]
How about now?

**Comment by aginamist** [comment]
Now the match is gone. Thank you!
