### ISSUE TITLE
window covers the sidebar

### ISSUE THREAD

**Issue by Slanfan** [Slanfan/MTG-Tolaria#396]
Hi! If I have a single window open (for example, "Matches"), they partially cover the sidebar, so it becomes hard to read the categories.

Thank you so much!
    
    Reporter: Andres Hojman
    ReporterUid: INK8HrQi6LPZIGH4p31S66XOYNN2
    RpoerterPlayerId: 1f888bdd-5396-4f0e-ac36-08ed82dd2a38

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/193424416-a89b7852-a13c-4a29-8659-ae8f5bd44898.png)

**Comment by Slanfan** [comment]
Is this what you are referring to?

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/240/commits/b941304149ff508f1561b650dc75091939e61144

**Comment by leriomaggio** [comment]
Unfortunately the same is happening to me on Mac OS and Chrome :(
I tried also Firefox and it's the same.

HTH

![Screenshot 2022-10-14 at 14 53 39](https://user-images.githubusercontent.com/1908453/195864197-a4071de8-e52f-4a94-bed1-acd757e7c035.png)
