### ISSUE TITLE
Full name header should appear on new message from same sender after x min.

### ISSUE THREAD

**Issue by Blazer** [Slanfan/MTG-Tolaria#4]
**Label = Improvement**
When posting messages in the event chat, if the same sender posts two messages in a row, the full name header doesn't show.

This is fine and intended to not clog up the space.

But this should be time dependent so that if there are two messages from the same sender (e.g the tournament organizer) with a long delay in between, it is hard to understand that there might have been hours, days, weeks between if the context is not clear.

So there should be a function that adds the full name header again for the first new chat message if x time has passed between the previous and new message.

**Comment by Slanfan** [comment]
![image](https://user-images.githubusercontent.com/9950323/101297381-05f9be80-3829-11eb-97e4-6629c5f2fc05.png)

If the time elapsed is more than 5min then the header will be shown again.
