### ISSUE TITLE
Don't cross the streams

### ISSUE THREAD

**Issue by gordonandersson** [Slanfan/MTG-Tolaria#41]
When opening a specatating tab for a match then open another the new videostreams actually goes to the earlier opened tab. So the old match tab actually keeps names, life and such from the originally opened match, but the cameras will be from the newly opened match.

**Comment by Slanfan** [comment]
I believe we have already fixed this by combining the match I'd and the player id. It's not yet deployed but should be soon. 

Previous solution just used the player is which is the same for all matches and therefore this could happen.

**Comment by Slanfan** [comment]
Correct me @JonnieHedkvist but I believe this is fixed.
