### ISSUE TITLE
Main organizer menu not fully accessible on small desktop resolutions

### ISSUE THREAD

**Issue by Narcism17** [Slanfan/MTG-Tolaria#422]
When the "Post pairings/Pair round/End round/etc." button it too long, vertically, for the screen resolution, there is no way to access the menu items that are cut-off. 

In my case, when using a small laptop, the menu was cut off just below "Reactivate previous round" so I could not access:
* Delete active pairings
* Manual Pairing
* Start Check-in
* Drop no-shows

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/pull/246/commits/e26016f6a47f55cee8251a39f450418933a00713
