### ISSUE TITLE
Standings not visible

### ISSUE THREAD

**Issue by Slanfan** [Slanfan/MTG-Tolaria#431]
Hi Slanfan, when looking at the standings of any online tournament, I only see my name and score and not the scores of all the others playing the tournament. Is there a way to reload so it becomes visible or is this a bug...

Cheers, Bas.
    
    Reporter: Bas van de Vijver (Beastiebas)
    ReporterUid: VqYm1E9QbCZkzOdTlURN2NztPrx1
    RpoerterPlayerId: 2b754b6b-55e2-49e7-bf00-53a3d5b418b0

**Comment by Baldrickus** [comment]
Same issue here. It works in MS Edge and not in Chrome.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/85223436/213868968-0995bfa3-a735-4a9f-a71b-5f2d24f5bf39.png">

**Comment by Baldrickus** [comment]
I have tried to reset Chrome to "factory default" but did not help.

**Comment by Slanfan** [comment]
@Baldrickus do you know how to open the developer console?

Is it Windows or MacOS?
