### ISSUE TITLE
Event Lobby links to Dashboard

### ISSUE THREAD

**Issue by albertberg** [Slanfan/MTG-Tolaria#498]
If I go to "Messages" from an old event and click on "Event Lobby" I am redirected to the "dashboard" instead of the event.

**Comment by Slanfan** [comment]
So you are visiting a message group for an event that is ended?

**Comment by Slanfan** [comment]
You know that you can access all your matches through the matches section as well. Filter by event, opponent etc. 

You also have some stats there with win% etc.
