### ISSUE TITLE
Feature request: enable/disable drop for in-person events

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#499]
People keep dropping by mistake in physical tournaments.
It would be great to have a toggle in the organizer dashboard (event settings) to allow or not the drop function for players in the reporting window.
If players had to go to the judge station to drop it would make everything easier.

**Comment by Slanfan** [comment]
This is much more intuitive in the new management flow. 

It also comes with a new reporting flow that eliminates this as you need to press and hold for 3 seconds to actually drop.
