### ISSUE TITLE
Sorting Pairings

### ISSUE THREAD

**Issue by Narcism17** [Slanfan/MTG-Tolaria#80]
It would be peachy if the Pairings panel sorted the pairings by Table number, in increasing order. :) 
No need for a button to toggle it in all kinds of different ways, I think this should be the default. 

Also, sorry, I don't know how to properly tag this post.

**Comment by Slanfan** [comment]
It's totally fine not being able to add labels. Not sure if you are at all ☺️

**Comment by Slanfan** [comment]
When fetching the data sorting should be applied directly before returning the data. 

All three getters should:
- Filter matches
- Sort matches
- Return the data 

**EventComponent**
Tolaria/src/app/components/events/event/event.component.ts

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/6528049bb1b3a8afc8da73b10c01e5324195a9ff

**Comment by Slanfan** [comment]
Will be released with milestone 0.9.0b
