### ISSUE TITLE
Custom avatar upload works but there is no confirmation

### ISSUE THREAD

**Issue by novalore** [Slanfan/MTG-Tolaria#97]
On MacOS 10.15.7 with Chrome 87.0.4280.141 when I click on upload after selecting an image file as custom avatar it appears as my avatar in the tiny icon on top right corner, but there is no confirmation of success, so the avarage user could think it didn't work or get confused.

**Comment by Slanfan** [comment]
Did the image load in the settings dialog?
If it was unclear, would it be sufficient with a messagetoast (small notification in the bottom) that stated "image uploaded and saved as your avatar"?

**Comment by Slanfan** [comment]
https://github.com/Slanfan/Tolaria/commit/581e98625f91d56f289095ede0da642120439882

**Comment by novalore** [comment]
> Did the image load in the settings dialog?
Yes, it did load.
> If it was unclear, would it be sufficient with a messagetoast (small notification in the bottom) that stated "image uploaded and saved as your avatar"?
A notification would surely be enough. Just some kind of confirmation that the action was successful

**Comment by Slanfan** [comment]
The fix is deployed. You should be able to try it out. Let me know what you think.
